### PR TITLE
🚑️ Use NSSharingServicePicker to resolve crash

### LINKED ISSUE #4929: A Control-click on a timeline entry crashes v7
This code causes the crash:

```swift
let standardServices = NSSharingService.sharingServices(forItems_noDeprecationWarning: items) as? [NSSharingService] ?? [NSSharingService]()
```

### PR DESCRIPTION
**Pull request by stuartbreckenridge**
Fixes #4929

- Always show a "Share..." menu, but disable it when necessary.
- `Share...` presents `NSSharingServicePicker` (similar to Toolbar)
- The `NSSharingServicePicker` is anchored to the trailing x coordinate of the selected row

### CODE REVIEW

File: Mac/MainWindow/Timeline/TimelineViewController+ContextualMenus.swift [hunk 1]
```diff
@@ -190,41 +190,31 @@ private extension TimelineViewController {
...
 		}
 
-		if let sharingMenu = shareMenu(for: articles) {
-			menu.addSeparatorIfNeeded()
-			let menuItem = NSMenuItem(title: sharingMenu.title, action: nil, keyEquivalent: "")
-			menuItem.submenu = sharingMenu
-			menu.addItem(menuItem)
-		}
+		menu.addSeparatorIfNeeded()
+		let shareButtonMenuItem = NSMenuItem(title: NSLocalizedString("Share...", comment: "Share..."), action: #selector(showShareSheet(_:)), keyEquivalent: "")
```
Comment (brentsimmons) [inline Mac/MainWindow/Timeline/TimelineViewController+ContextualMenus.swift]: Style nit: instead of three dots ... we should use a single ellipsis character … which you can type using option-;
